In [18]:
import pandas as pd
import numpy as np
import json
import ast
import os

In [19]:
PREPATH = '../Data/PreProcessed/'
POSPATH = '../Data/PosProcessed/'
CLASSPATH = '../Data/Classification/'
UDERREVIEWPATH = '../Data/UndeRreview/'

---

#### **01 ) - Split's**

---

---

##### A ) Split para o PosDatasetsClean.csv

In [ ]:
df_pos = pd.read_csv(os.path.join(POSPATH,"PosDatasetsClean.csv"))
df_clear = df_pos[df_pos['is_encrypted'] == 0].copy()
df_clear['Columns'] = df_clear['Columns'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
df_input_macro = df_clear[['id', 'Columns']].explode('Columns').rename(columns={'Columns': 'Col'})
df_input_macro = df_input_macro.dropna(subset=['Col'])
df_input_macro.to_csv(os.path.join(UDERREVIEWPATH, 'SplitPosDatasets_UR.csv'), index=False)
df_input_macro.head()

         id             Col
0  CRED-002          status
0  CRED-002        duration
0  CRED-002  credit_history
0  CRED-002         purpose
0  CRED-002          amount

---

##### B ) Instânciando Taxonomia do Artigo

In [26]:
df_article_vars = pd.read_excel(os.path.join(PREPATH, 'PreArticleVars.xlsx'))
df_article_vars['Nome das variáveis'] = df_article_vars['Nome das variáveis'].str.replace('\n', '').str.split(',')
df_article_vars_tidy = df_article_vars.explode('Nome das variáveis')
df_article_vars_tidy['Nome das variáveis'] = df_article_vars_tidy['Nome das variáveis'].str.strip()

df_article_vars_tidy = df_article_vars_tidy[['Nome das variáveis', 'Grupo de Variáveis']]

df_article_vars_tidy.to_csv(os.path.join(POSPATH, 'PosArticleVars.csv'), index=False)
df_article_vars_tidy.head()

              Nome das variáveis Grupo de Variáveis
0                 Home ownership      SOCIOECONOMIC
0  number of children/dependents      SOCIOECONOMIC
0                 household size      SOCIOECONOMIC
0           length of employment      SOCIOECONOMIC
0              employment status      SOCIOECONOMIC

---

##### C ) Split para o MacroClassificationTaxonomy.csv

In [25]:
df_standardized_vars = pd.read_csv(os.path.join(CLASSPATH, 'MacroTaxonomyClassification.csv'))
df_standardized_vars.head()

,id,URL,Col,Col_Standardized
0,CRED-002,https://www.kaggle.com/datasets/sid321axn/sout...,status,INSTITUTIONAL and FINANCIAL
1,CRED-002,https://www.kaggle.com/datasets/sid321axn/sout...,duration,INSTITUTIONAL and FINANCIAL
2,CRED-002,https://www.kaggle.com/datasets/sid321axn/sout...,credit_history,INSTITUTIONAL and FINANCIAL
3,CRED-002,https://www.kaggle.com/datasets/sid321axn/sout...,purpose,INSTITUTIONAL and FINANCIAL
4,CRED-002,https://www.kaggle.com/datasets/sid321axn/sout...,amount,INSTITUTIONAL and FINANCIAL

In [24]:
df_split_standardized_vars = df_standardized_vars[df_standardized_vars['Col_Standardized'] != 'UNCLASSIFIED'][['id', 'Col', 'Col_Standardized']].copy()
df_split_standardized_vars.to_csv(os.path.join(UDERREVIEWPATH, 'SplitMacroTC_UR.csv'), index=False)
df_split_standardized_vars.head()

         id             Col             Col_Standardized
0  CRED-002          status  INSTITUTIONAL and FINANCIAL
1  CRED-002        duration  INSTITUTIONAL and FINANCIAL
2  CRED-002  credit_history  INSTITUTIONAL and FINANCIAL
3  CRED-002         purpose  INSTITUTIONAL and FINANCIAL
4  CRED-002          amount  INSTITUTIONAL and FINANCIAL